sudo: required
language: ruby
rvm: 1.29.9

services:
  - docker

cache: bundler

env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - gem update --system
  - gem install bundler
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
