version: '3.6'

volumes:
  assets:
  uploads:
  invoices:
  exports:
  plugins:
  log:

services:
  makernet:
    image: mattkenigson/makernet.work
    environment:
      RAILS_ENV: production
      RACK_ENV: production
    env_file:
      - ${PWD}/config/env
    volumes:
      - assets:/usr/src/app/public/assets
      - uploads:/usr/src/app/public/uploads
      - invoices:/usr/src/app/invoices
      - exports:/usr/src/app/exports
      - log:/var/log/supervisor
      - plugins:/usr/src/app/plugins
    depends_on:
      - postgres
      - redis
      - elasticsearch
    restart: always

  postgres:
    image: postgres:10.3-alpine
    volumes:
      - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always

  elasticsearch:
    image: elasticsearch:5.6.9-alpine
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ${PWD}/elasticsearch:/usr/share/elasticsearch/data
    restart: always

  redis:
    image: redis:3.2.11-alpine
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - ${PWD}/redis:/data
    restart: always

  nginx:
    image: nginx:1.13.12-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/config/nginx:/etc/nginx/conf.d
      - ${PWD}/letsencrypt/etc:/etc/letsencrypt
      - ${PWD}/log:/var/log/nginx
      - assets:/usr/src/app/public/assets:ro
      - uploads:/usr/src/app/public/uploads:ro
      - invoices:/usr/src/app/invoices:ro
      - exports:/usr/src/app/exports:ro
      - log:/var/log/supervisor:ro
      - plugins:/usr/src/app/plugins:ro
    links:
      - makernet:makernet
    restart: always
