version: '2'
services:
  makernet:
    image: akaiiro/makernet-sample
    environment:
      RAILS_ENV: production
      RACK_ENV: production
    env_file:
      - ${PWD}/config/env
    volumes:
      - ${PWD}/public/assets:/usr/src/app/public/assets
      - ${PWD}/public/uploads:/usr/src/app/public/uploads
      - ${PWD}/invoices:/usr/src/app/invoices
      - ${PWD}/exports:/usr/src/app/exports
      - ${PWD}/log:/var/log/supervisor
      - ${PWD}/plugins:/usr/src/app/plugins
    depends_on:
      - postgres
      - redis
      - elasticsearch
    restart: always

  postgres:
    image: postgres:10.3
    volumes:
      - ${PWD}/postgresql:/var/lib/postgresql/data
    restart: always

  elasticsearch:
    image: elasticsearch:5.6.8
    volumes:
      - ${PWD}/elasticsearch:/usr/share/elasticsearch/data
    restart: always

  redis:
    image: redis:3.2.11
    volumes:
      - ${PWD}/redis:/data
    restart: always

  nginx:
    image: nginx:1.13.12
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/config/nginx:/etc/nginx/conf.d
      - ${PWD}/letsencrypt/etc:/etc/letsencrypt
      - ${PWD}/log:/var/log/nginx
    volumes_from:
      - makernet:ro
    links:
      - makernet:makernet
    restart: always
