# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_signing_secret: <%= ENV["STRIPE_SIGNING_SECRET"] %>
  stripe_currency: <%= ENV["STRIPE_CURRENCY"] %>
  disqus_shortname: <%= ENV["DISQUS_SHORTNAME"] %>
  fablab_without_plans: <%= ENV["FABLAB_WITHOUT_PLANS"] %>
  fablab_without_spaces: <%= ENV["FABLAB_WITHOUT_SPACES"] %>
  default_host: <%= ENV["DEFAULT_HOST"] %>
  default_protocol: <%= ENV["DEFAULT_PROTOCOL"] %>
  delivery_method: <%= ENV["MAIL_DELIVERY_METHOD"] %>
  time_zone: <%= ENV["TIME_ZONE"] %>
  week_starting_day: <%= ENV["WEEK_STARTING_DAY"] %>
  d3_date_format: <%= ENV["D3_DATE_FORMAT"].dump %>  # .dump is needed as the value may start by a '%', see https://github.com/tenderlove/psych/issues/75
  uib_date_format: <%= ENV["UIB_DATE_FORMAT"] %>
  excel_date_format: <%= ENV["EXCEL_DATE_FORMAT"]%>
  rails_locale: <%= ENV["RAILS_LOCALE"] %>
  app_locale: <%= ENV["APP_LOCALE"] %>
  moment_locale: <%= ENV["MOMENT_LOCALE"] %>
  summernote_locale: <%= ENV["SUMMERNOTE_LOCALE"] %>
  angular_locale: <%= ENV["ANGULAR_LOCALE"] %>
  messageformat_locale: <%= ENV["MESSAGEFORMAT_LOCALE"] %>
  fullcalendar_locale: <%= ENV["FULLCALENDAR_LOCALE"] %>
  elasticsearch_language_analyzer: <%= ENV["ELASTICSEARCH_LANGUAGE_ANALYZER"] %>
  openlab_app_secret: <%= ENV["OPENLAB_APP_SECRET"] %>
  openlab_app_id: <%= ENV["OPENLAB_APP_ID"] %>
  openlab_base_uri: <%= ENV["OPENLAB_BASE_URI"] %>
  navinum_api_login: <%= ENV["NAVINUM_API_LOGIN"] %>
  navinum_api_password: <%= ENV["NAVINUM_API_PASSWORD"] %>
  log_level: <%= ENV["LOG_LEVEL"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  elaticsearch_host: <%= ENV["ELASTICSEARCH_HOST"] %>
  max_image_size: <%= ENV["MAX_IMAGE_SIZE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_user_name: <%= ENV["SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
